proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

grpc_options:

  port: 9000

  grpc_servicer_functions: []

logging_config:

  encoding: TEXT

  log_level: INFO

  logs_dir: null

  enable_access_log: true

applications:

- name: bgremover

  route_prefix: /bgremover

  import_path: main:app

  runtime_env:
    working_dir: /ray_serve

  deployments:

  - name: BGRemover
    autoscaling_config:
      min_replicas: 0
      initial_replicas: null
      max_replicas: 4
      target_ongoing_requests: 2
      metrics_interval_s: 10.0
      look_back_period_s: 30.0
      smoothing_factor: 1.0
      upscale_smoothing_factor: null
      downscale_smoothing_factor: null
      upscaling_factor: null
      downscaling_factor: null
      downscale_delay_s: 600.0
      upscale_delay_s: 30.0
    ray_actor_options:
      num_cpus: 4.0
      num_gpus: 1.0
